### ISSUE TITLE
Error message when ssid is not found

### ISSUE THREAD

**Issue by mmalte** [ffac/gluon-ssid-changer#1]
When the ssid need to be changed the first "cut" gets an empty value from the "grep".

This is not harmful, but don't look nice.

> CURRENT_SSID=`grep "^ssid=$ONLINE_SSID" $HOSTAPD | cut -d"=" -f2`

**Comment by viisauksena** [comment]
follow this - as done in previous merge request (just change to CURRENT_SSID)
: ${ONLINE_SSID:=FREIFUNK}   # if for whatever reason ONLINE_SSID is NULL

**Comment by mmalte** [comment]
Solved by #19
