### ISSUE TITLE
problem with TQ shortly after boot

### ISSUE THREAD

**Issue by rotanid** [ffac/gluon-ssid-changer#21]
if a node boots, the TQ doesn't start with 100 so it happens often, that the SSID is changed to FF_OFFLINE_... although the node has a good connection.
you then have to wait for the TQ to rise high enough to get the "original" SSID back

**Comment by Metatron321** [comment]
True, but how should the script know if the the TQ is low in general (connection issues) or just because it is still rising to 100 after the boot?

**Comment by mmalte** [comment]
The link quality starts with 0 and needs some time to rise. It's perfectly fine if the offline ssid is used until the link quality is sufficient. 

In fact I would like to set the offline ssid at boottime.
