### ISSUE TITLE
No rule to make target 'package/gluon-ssid-changer/compile

### ISSUE THREAD

**Issue by rubo77** [ffac/gluon-ssid-changer#22]
Ich bekomme diesen Fehler, wenn ich versuche das Paket mit 2016.1.5 zu bauen:

```
make package/gluon-ssid-changer/compile V=s
```

ich hab auch schon probiert, das Makefile und den `files` folder in einen weiteren Unterordner `gluon-ssid-changer` zu legen, aber selber Fehler. Der selbe Fehler kommt auch, wenn ich das Makefile ganz lösche.

was mache ich falsch?

Oder funktioniert das so nicht unter 2016.1.5?

**Comment by rubo77** [comment]
Dies ist die site.conf, die ich benutze und ohne den ssid-changer funktioniert diese auch erfolgreich:
https://github.com/rubo77/site-ffki/tree/ssid-changer

**Comment by mmalte** [comment]
Das ist seltsam, wir verwenden seit geraumer Zeit 2016.1.5 ohne auf Probleme gestoßen zu sein.

Hast mal versucht mit unserer site zu bauen?

Auf den ersten Blick frage ich mich ob es ein Problem sein könnte, dass in eurer SSID / vorkommen.

**Comment by mmalte** [comment]
Ich habe allerdings auch noch nie versucht das Paket einzeln zu bauen.

**Comment by rubo77** [comment]
Wie gesagt: Ich kann die firmware ja bauen, nur halt einzeln nicht. mit anderen modulen funktioniert das einzeln bauen. sehr praktisch um Fehler gleich zu erkennen und nicht immer 15 minuten warten zu müssen bis die gesamte firmware beim Bauen abbricht

**Comment by rubo77** [comment]
schwer nachzuvollziehen, was da schief ging, vielleicht hatte icheinen fehler in 

```
GLUON_SITE_FEEDS
```
