### ISSUE TITLE
SSID nicht wechseln, sondern nur eine zusätzliche SSID

### ISSUE THREAD

**Issue by rubo77** [ffac/gluon-ssid-changer#23]
Wir würden gern die normale SSID immer weiter laufen lassen um das lokale Netz nicht zu stören, falls die Verbindung mal abbricht, aber zur info würden wir gern eine weitere SSID ausstrahlen, sobald die Verbindung zum Gateway abbricht "Freifunk Knoten ... offline!"

Was müsste man ändern/ergänzen, um dies zu erreichen?

vielleicht könnte man dies als option in der site.conf einbauen

**Comment by mmalte** [comment]
Die Intention des ssid-changer ist unbedarfte User aus dem nicht funktionierenden Netz zu werfen.

Das schließt aus die default SSID aktiv zu lassen.

Wenn du auf deinem Knoten manuell eine zusätzliche Client SSID hinzufügst wird diese nicht geändert.

**Comment by rubo77** [comment]
Wir versuchen das gerade hier: https://forum.freifunk.net/t/wie-erstellt-man-in-einem-gluon-router-eine-zweite-ssid/13205/4

Aber irgendwie klappt das noch nicht, vielleicht kannst du uns dort einen tipp geben, wei man eine zusätzliche SSID startet?

**Comment by rubo77** [comment]
Ich hab mal aus eurem Modul ein neues entwickelt hier im branch: 
https://github.com/rubo77/gluon-ssid-changer/tree/ssid-notifier
