### ISSUE TITLE
sed: bad option in substitution expression

### ISSUE THREAD

**Issue by rubo77** [ffac/gluon-ssid-changer#24]
Ich habe einen router mit dem Namen "RouterMitVielZuLangemNamenDerInAllenListenTotalNervt"

unsere SSID ist "http://kiel.freifunk.net/"

Wenn ich auf der Konsole das script aufrufe:

```
/lib/gluon/ssid-changer/ssid-changer.sh
```

kommt dieser Fehler:

```
... node is considered offline
sh: FF_OFFLINE_RouterMi...talNervt: unknown operand
gluon-offline-ssid: TQ is 220, SSID is http://kiel.freifunk.net/, change to FF_OFFLINE_RouterMi...talNervt
sed: bad option in substitution expression
HUP!

```

**Comment by mruettgers** [comment]
Könntest Du den ssid-changer mal mit `sh -x /lib/gluon/ssid-changer/ssid-changer.sh` aufrufen?

**Comment by rubo77** [comment]
Der Fehler liegt hier: https://github.com/ffac/gluon-ssid-changer/blob/master/files/lib/gluon/ssid-changer/ssid-changer.sh#L69

Dies repariert dies:

```
            sed -i "s~^ssid=$ONLINE_SSID~ssid=$OFFLINE_SSID~" $HOSTAPD
```

Eine SSID mit schrägstrichen beendet sonst die sed teiler. Wenn man tilde als teiler benutzt ist dies unwahrscheinlicher.

(Eigentlich muesste man vorher in der SSID nach dem trennzeichen suchen)

**Comment by mruettgers** [comment]
Ok, das macht Sinn, wenn die aktuelle oder die gewünschte SSID Slashes enthält. Der Fix funktioniert, solange die SSID keine ~ beinhaltet. Vielleicht bietet die Bash ja die Möglichkeit Strings für die Benutzung in RegExps zu maskieren.

**Comment by rubo77** [comment]
Allerdings weis ich noch nicht, wo das "sh: FF_OFFLINE_RouterMi...talNervt: unknown operand" her kommt, aber scheint auch nicht zu schaden

**Comment by mruettgers** [comment]
Das sollte ein Aufruf mit `sh -x` zeigen.
