### ISSUE TITLE
change SSID only after timeout

### ISSUE THREAD

**Issue by rubo77** [ffac/gluon-ssid-changer#26]
Bei einem schwach angebundenen Router, wenn die SSID sich ständig wechselt, macht es das schwer,  sich auf dem Router per Wlan zu verbinden, um auf der Konsole was zu ändern. Besser wäre, wenn sich die SSID erst nach einem Timeout von z.B. 5 Minuten zu offline ändern würde.

Dazu könnte man (nach https://github.com/ffac/gluon-ssid-changer/issues/4#issuecomment-173581235) eine var in `/tmp/count_ssid_off` schreiben (ram):

```
if [ ! -f /tmp/count_ssid_off ]; then 
  echo 0 > /tmp/count_ssid_off
fi
OFFCOUNT=$(cat /tmp/count_ssid_off)
let i=$(OFFCOUNT)+1 ; echo $i > /tmp/count_ssid_off
```

und statt immer gleich zu wechseln, einfach

```
TIMEOUT=5
if [ "$OFFCOUNT" -gt "$TIMEOUT" ]; then
  ... change SSID
fi
```

oder so ähnlich

**Comment by mmalte** [comment]
Das finde ich überraschend und habe ich so noch nicht beobachtet.

Einerseits wird von Batman gezählt, es gibt also Sprünge sondern nur kontinuierliche Veränderungen des TQ, andererseits habe ich einen Schmitt Trigger implementiert um ein allzu häufiges toggeln zu vermeiden.

**Comment by mmalte** [comment]
Kann es sein, dass das häufige toggeln durch eine instabile VPN Verbindung entsteht?

Durch den Wegfall des Interface kann sich die TQ abrupt ändern.

**Comment by rubo77** [comment]
Das mit dem an-aus, war nur eine Befürchtung. Ich habe den changer bei uns ja noch gar nicht implementiert.

Ich hätte nur gerne zusätzlich zum Schmitt Trigger so einen konfigurierbaren Timeout Wert.

Den könnte man dann nämlich auch auf z.B. 10 Stunden setzen, wodurch ein Router erst nachdem er 10 Stunden offline ist, seine SSID auf offline ändern würde.

Das würde den Impact des ssid-changers minimieren in Communities, wo erwünscht ist, dass Router auch, wenn sie kein Gateway erreichen trotzdem weiter erreichbar sind.
