### ISSUE TITLE
Patch für Gluon 2017

### ISSUE THREAD

**Issue by AKA-47** [ffac/gluon-ssid-changer#32]
Moin.
Ich habe eben den SSID-Changer für die Gluon 2017 anpassen müssen.
Das in neueren batman Versionen das gewählte Gateway mit => anstatt * markiert wird habt ihr ja schon gepatcht. 
Was noch fehlt ist das das uci jetzt in der 2017er die parameter "vorne" erwartet.
man muss also 
ONLINE_SSID=$(uci get wireless.client_radio0.ssid -q)
durch
ONLINE_SSID=$(uci -q get wireless.client_radio0.ssid)
ersetzen.
bei uns ist 
: ${ONLINE_SSID:=FREIFUNK} # if for whatever reason ONLINE_SSID is NULL
durch 
: ${ONLINE_SSID:=Freifunk} # if for whatever reason ONLINE_SSID is NULL
ersetzt worden weil wir eine andere SSID nutzen.

Gruss

**Comment by mmalte** [comment]
Ich habe Mittlerweile die umfangreichen Anpassungen im Fork aus Freifunk Nord in unser Repo übernommen. Diese Version ist auch mit 2017.x kompatibel.
