### ISSUE TITLE
Use SSID from site.conf or UCI

### ISSUE THREAD

**Issue by SISheogorath** [ffac/gluon-ssid-changer#8]
Most Freifunk Communities doesn't use only "Freifunk" as SSID because it may cause trouble if Communities are overlapping.

So it should use SSID from Site.conf or preferly uci.

**Comment by mmalte** [comment]
It would be easy to use the primary ssid 2.4Ghz from the site.conf

In communities with different SSIDs for 5 and 2.4Ghz the 5 GHz SSID would be overwritten.

**Comment by mmalte** [comment]
Well it's easy to read the ssid from /lib/gluon/site.conf during runtime. Would be much greater to modify the script during installation, does anybody know how to do that?

**Comment by mruettgers** [comment]
```
SSID=$(lua -e "site = require 'gluon.site_config'; print(site.wifi24.ssid)")
```

**Comment by SunrabbitDE** [comment]
I think is a better way to read die site.conf instead of modify the script during installation.

If you change the ssid in site.conf it should be used in your script. If you have the ssid defined in more than one place, you have to edit more than one file to change you ssid. thats bad.

**Comment by viisauksena** [comment]
look at pull request ..  this should do the job 
which take the real actual value out of the config and work with that - so any later changes by whoever will be ok - setting this at building time is not usefull.
if value is NULL there is a fallback to FREIFUNK - as it is now hardcoded

**Comment by viisauksena** [comment]
while the 5ghz different from 2,4 ghz naming  issue remain, in general this is solved, or?

**Comment by mmalte** [comment]
Well, my original plan was to read the site.conf during the build process.

I've asked the gluon developers about the possible ways to do this, it turned out that your way is referred by the gluon team.

So you are perfectly right, the isse is closed.
